-- Add photo column to measurement and tracking tables
ALTER TABLE feedings ADD COLUMN IF NOT EXISTS photo TEXT DEFAULT '';
ALTER TABLE sleep ADD COLUMN IF NOT EXISTS photo TEXT DEFAULT '';
ALTER TABLE changes ADD COLUMN IF NOT EXISTS photo TEXT DEFAULT '';
ALTER TABLE tummy_times ADD COLUMN IF NOT EXISTS photo TEXT DEFAULT '';
ALTER TABLE temperature ADD COLUMN IF NOT EXISTS photo TEXT DEFAULT '';
ALTER TABLE weight ADD COLUMN IF NOT EXISTS photo TEXT DEFAULT '';
ALTER TABLE height ADD COLUMN IF NOT EXISTS photo TEXT DEFAULT '';
ALTER TABLE head_circumference ADD COLUMN IF NOT EXISTS photo TEXT DEFAULT '';
ALTER TABLE pumping ADD COLUMN IF NOT EXISTS photo TEXT DEFAULT '';
ALTER TABLE medications ADD COLUMN IF NOT EXISTS photo TEXT DEFAULT '';
ALTER TABLE notes ADD COLUMN IF NOT EXISTS photo TEXT DEFAULT '';
